name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^6.2.1
  intl: ^0.19.0
  get_it_mixin: ^4.2.2
  flutter_otp_text_field: ^1.1.3+2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  jwt_decoder: ^2.0.1
  file_picker: ^9.0.2
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  universal_platform: ^1.1.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
